### ISSUE TITLE
/bin/bash: C:actions-runner_work_actionsad-mgithub-push-actionv0.6.0start.sh: No such file or directory

### ISSUE THREAD

**Issue by albintho** [ad-m/github-push-action#103]
when i tried to run github-push-action on a self hosted windows machine, Im getting the below error, Could someone help me understand this.

Run ad-m/github-push-action@v0.6.0
Started: bash C:\actions-runner\_work\_actions\ad-m\github-push-action\v0.6.0\start.sh
/bin/bash: C:actions-runner_work_actionsad-mgithub-push-actionv0.6.0start.sh: No such file or directory
Error: Invalid status code: 127
    at ChildProcess.<anonymous> (C:\actions-runner\_work\_actions\ad-m\github-push-action\v0.6.0\start.js:9:19)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5) {
  code: 127
}
Error: Invalid status code: 127
    at ChildProcess.<anonymous> (C:\actions-runner\_work\_actions\ad-m\github-push-action\v0.6.0\start.js:9:19)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)

**Comment by ZPascal** [comment]
I suspect that Bash isn't installed or there's something wrong with the script path. I need more information to analyze the problem. 

I'm going to close this ticket since it's more than 5 years old. Feel free to reopen the issue if the problem persists.
