### ISSUE TITLE
remote: Permission to git denied to github-actions[bot].

### ISSUE THREAD

**Issue by Shaquu** [ad-m/github-push-action#96]
Hi,
I am trying to push changes but like you will see it fails due to some errors.

Test run is here:
https://github.com/NRCHKB/node-red-contrib-homekit-docker/runs/3194895671?check_suite_focus=true

Error
```
Run ad-m/github-push-action@master
  with:
    github_token: ***
    branch: refs/pull/42/merge
    directory: .
Push to branch refs/pull/42/merge
remote: Permission to NRCHKB/node-red-contrib-homekit-docker.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/NRCHKB/node-red-contrib-homekit-docker.git/': The requested URL returned error: 403
Error: Invalid exit code: 128
    at ChildProcess.<anonymous> (/home/runner/work/_actions/ad-m/github-push-action/master/start.js:29:21)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5) {
  code: 128
}
Error: Invalid exit code: 128
    at ChildProcess.<anonymous> (/home/runner/work/_actions/ad-m/github-push-action/master/start.js:29:21)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
```

Part of the gh action:
```yml
  dependabot:
    #needs: [build]
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
      - run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          npm version patch -m "[RELEASE] %s"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
      - uses: fastify/github-action-merge-dependabot@v2.1.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by ad-m** [comment]
Do you have organisation restriction? Is that branch protected?

**Comment by Shaquu** [comment]
I am trying to push to dependapot pr branch. There should be no limits on that.
Maybe I am passing branch incorrectly.

**Comment by ad-m** [comment]
Looks mention:
```
GITHUB_TOKEN Permissions
  Actions: read
  Checks: read
  Contents: read
  Deployments: read
  Discussions: read
  Issues: read
  Metadata: read
  Packages: read
  PullRequests: read
  RepositoryProjects: read
  SecurityEvents: read
  Statuses: read
```

Default is:

```

GITHUB_TOKEN Permissions
  Actions: write
  Checks: write
  Contents: write
  Deployments: write
  Discussions: write
  Issues: write
  Metadata: read
  Packages: write
  PullRequests: write
  RepositoryProjects: write
  SecurityEvents: write
  Statuses: write
```
See https://github.com/ad-m/cbosa/runs/3197304980?check_suite_focus=true .

Something is restricting permission. 

What do you have at https://github.com/NRCHKB/node-red-contrib-homekit-docker/settings/actions in "Workflow permissions" section?

**Comment by Shaquu** [comment]
@ad-m here it is, says read and write
![image](https://user-images.githubusercontent.com/2881159/127678772-776865c9-ca74-449b-a6df-8e95a0471560.png)

**Comment by Shaquu** [comment]
Okay, I see the issue. Dependabot is pushing from fork. It is why permissions are limited.

**Comment by Shaquu** [comment]
@ad-m update.
I have used custom token:
```
        with:
          github_token: ${{ secrets.DEPENDABOT_TOKEN }}
```
It is defined on repo level
![image](https://user-images.githubusercontent.com/2881159/127686027-26b9b312-fea0-4b0d-aec0-5fc1e44e6243.png)

I receive new error from your action:
`Missing input "github_token: ${{ secrets.GITHUB_TOKEN }}".`

**Comment by ad-m** [comment]
> Note: With the exception of GITHUB_TOKEN, secrets are not passed to the runner when a workflow is triggered from a forked repository.

See [Using encrypted secrets in a workflow](https://docs.github.com/en/actions/reference/encrypted-secrets#using-encrypted-secrets-in-a-workflow)

> Something is restricting permission.

See "Maximum access
by forked repos" in [Permissions for the GITHUB_TOKEN](https://docs.github.com/en/actions/reference/authentication-in-a-workflow#permissions-for-the-github_token)

I suggest - in your scenario – using the "push" event instead of "pull_request" and using GITHUB_TOKEN. Then the "push" event will be executed in the context of the source repository  (repository that is fork), so it will be a local operation and will be a full write to the local repository.

**Comment by Shaquu** [comment]
Just to clarify. I am merging between branches on the same repo.

Solution might be to extend permissions for GitHub token per job:
https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#permissions

**Comment by ad-m** [comment]
Thank for you clarification. It makes a big different.

I don't understand why extends of permission for GitHub token is required in your scenario. In my experience, the token should have the necessary "read / write" permissions currently. I already shared information permission of one of my job on personal repository.

Setting up permission in a workflow can potentially solve the problem, but it's worth understanding why it is required in this case.Setting up permission in a workflow can potentially solve the problem, but it's worth understanding why it is required in your case.

GitHub documentation mention: 

> People with admin permissions to an enterprise, organization, or repository can set the default permissions to be either permissive or restricted. 

Could you verify that in your organisation?

**Comment by noxxious** [comment]
@Shaquu ran into the same issue here and it seems it is a limitation of the way dependabot works and there's a note in Github docs

`Note: Workflow runs triggered by Dependabot pull requests run as if they are from a forked repository, and therefore use a read-only GITHUB_TOKEN. These workflow runs cannot access any secrets. See "Keeping your GitHub Actions and workflows secure: Preventing pwn requests" for strategies to keep these workflows secure.`
https://docs.github.com/en/actions/reference/authentication-in-a-workflow#permissions-for-the-github_token

**Comment by noxxious** [comment]
It seems also you can manage this behavior in your organization action settings "Fork pull request workflows in private repositories" -> "Send secrets to workflows from fork pull requests."

**Comment by lixuguang** [comment]
I have the same problem

**Comment by siegfault** [comment]
I ran into this issue while trying to solve the same problem. In case it's helpful, I found some good examples that helped me resolve it. What @noxxious said, that dependabot by default has a readonly token, is true, but it looks like adding a top-level entry allows us to change that:
```yml
permissions:
  pull-requests: write
  issues: write
  repository-projects: write
```

See:
* https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#changing-github_token-permissions
* https://github.com/dependabot/fetch-metadata#usage-instructions

**Comment by SamYuan1990** [comment]
```
permissions:
  pull-requests: write
  contents: write
  repository-projects: write
```

Hi team,

I tried permissions above but it won't work.
is there any guidance to set up / check the permissions?
for example if the branch protected or workflow permissions?

**Comment by SamYuan1990** [comment]
> Hi @SamYuan1990,
> 
> as far as I know, it should work with the corresponding rules. Could you please describe your setup and post the corresponding error message?

Hi @ZPascal , we find a bot account to avoid this issue.

We once have a rule for commit on default branch should have a pr back.

and then, the issue appears as push back without a pr.

**Comment by ZPascal** [comment]
Hi @SamYuan1990, could you please share the scopes of the token and the used GitHub Action configuration to reproduce the error?

**Comment by angeldollface** [comment]
> @ad-m here it is, says read and write ![image](https://user-images.githubusercontent.com/2881159/127678772-776865c9-ca74-449b-a6df-8e95a0471560.png)
> 
> In your reference (cbosa run), you were pushing to master, I am trying to push to PR branch.

For anyone else getting a `Permission denied` error: This fixed it for me.

**Comment by smallyunet** [comment]
Why I can't select the above option? It's disabled.
<img width="798" alt="Screenshot 2023-01-16 at 12 02 40" src="https://user-images.githubusercontent.com/20765689/212596304-084deea6-f9a4-4d4b-93fe-bf739691e45b.png">

**Comment by dacanizares** [comment]
You can enable that option under ORGANIZATION settings not REPO settings.

**Comment by allefzy** [comment]
After practically 1 hour trying solve "remote: Permission to (...) denied to github-actions[bot]."
I went to Settings > Actions > General, and voala. The option "Read repository contents permission" was selected insteed of "Read and write permissions".
![image](https://user-images.githubusercontent.com/106132039/213337522-e4494da2-387a-4759-b59f-96c5990892b2.png)
If the "Read and write permissions" is the default settings, why was mine in just "Read"? 🤔

Anyway, if someone come across the same problem, I hope that my comment helps.

**Comment by Ecupse** [comment]
i have similar issues. I am the owner of the repo. I have set workflow permission to read and write. the branch is not protected. i have added pull-requests: write,  issues: write, repository-projects: write
GHA error
Run ad-m/github-push-action@master
Push to branch main
remote: Write access to repository not granted.

**Comment by ZPascal** [comment]
@Ecupse You want to push inside the same repository or a different as on the executed action?

**Comment by Ecupse** [comment]
> @Ecupse You want to push inside the same repository or a different as on the executed action?
This is my GHA yml. everything runs until the commit and push part. Thanks for your comments.

name: Sync S3 Object

on:
  push:
    paths:
      - 'text/**'    
env:
  BUCKET_NAME : "somename"
  AWS_REGION : "us-east-1"
  # These permissions are needed to interact with GitHub's OIDC Token endpoint.
permissions:
      id-token: write
      contents: read
      actions: write
      checks: write
      pull-requests: write
      issues: write
      repository-projects: write
jobs:
  deploy:
    name: Sync to Amazon S3
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Configure AWS credentials from Dev account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::somenumber:role/github-actions-role
        aws-region: ${{ env.AWS_REGION }}

    - name: Copy files to the test website with the AWS CLI
      run: |
        aws s3 sync s3://${{ env.BUCKET_NAME }} text/
    - name: Commit and push changes
      run: |
        git config --global user.name "name"
        git config --global user.email "somename@name.com"
        git add -A
        git commit -m "update text"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main

**Comment by Ecupse** [comment]
> @Ecupse You want to push inside the same repository or a different as on the executed action?

> @Ecupse You want to push inside the same repository or a different as on the executed action?
This is my GHA yml. everything runs until the commit and push part. Thanks for your comments.

    name: Sync S3 Object

    on:
      push:
        paths:
          - 'text/**'    
    env:
      BUCKET_NAME : "somename"
      AWS_REGION : "us-east-1"
            id-token: write
            contents: read
            actions: write
            checks: write
            pull-requests: write
            issues: write
           repository-projects: write
    jobs:
      deploy:
        name: Sync to Amazon S3
        runs-on: ubuntu-latest

        steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Configure AWS credentials from Dev account
          uses: aws-actions/configure-aws-credentials@v1
          with:
            role-to-assume: arn:aws:iam::somenumber:role/github-actions-role
            aws-region: ${{ env.AWS_REGION }}

        - name: Copy files to the test website with the AWS CLI
          run: |
            aws s3 sync s3://${{ env.BUCKET_NAME }} text/
        - name: Commit and push changes
          run: |
            git config --global user.name "name"
            git config --global user.email "somename@name.com"
            git add -A
            git commit -m "update text"
        - name: Push changes
          uses: ad-m/github-push-action@master
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            branch: main

**Comment by ZPascal** [comment]
@Ecupse You're aware that you're not pushing inside the feature branch and try to push to the main branch directly, right? Do you have checked if there are any restriction like protected branch to push directly to the main branch?

**Comment by Ecupse** [comment]
> @Ecupse You want to push inside the same repository or a different as on the executed action?

I amanged to trouble shoot my issue after changing my repo from private to public  and adding the whole list of permission below.

permissions:
      id-token: write
      contents: write
      actions: write
      checks: write      
      deployments: write
      discussions: write
      issues: write
      pages: read
      packages: write
      pull-requests: write
      repository-projects: write
      security-events: write
      statuses: write

**Comment by ZPascal** [comment]
@Ecupse Great to hear that. I think, it should be theoretically also be possible to push to a private repository.

**Comment by Ecupse** [comment]
> @Ecupse Great to hear that. I think, it should be theoretically also be possible to push to a private repository.

I would be grateful if you can suggest some ways i can look into that. When i had my repo as private i had the original error . Any suggestions would be helpful.

> GHA error
> Run ad-m/github-push-action@master
> Push to branch main
> remote: Write access to repository not granted.

**Comment by IEvangelist** [comment]
All you should need is:

```yml
permissions:
  contents: write
  issues: write
  pull-requests: write
```

**Comment by officialbishowb** [comment]
Hi, I had the same problem and the solution to this problem should be by using your personal access token. Generate a personal access token under developer settings. Then in your source repo (where your action file is located), add the personal access token under Settings > Secrets and Variables > Actions and click on the "New Repo... secret" button at the top and add the token with something like PA_TOKEN. Then replace the GITHUB_TOKEN in the action file with PA_TOKEN. It should then work. I also tried with setting the permissions & co but the fix was the personal access token for me.

**Comment by DanielAlexssander** [comment]
> @ad-m here it is, says read and write ![image](https://user-images.githubusercontent.com/2881159/127678772-776865c9-ca74-449b-a6df-8e95a0471560.png)
> 
> In your reference (cbosa run), you were pushing to master, I am trying to push to PR branch.

where is this?

**Comment by ZPascal** [comment]
@DanielAlexssander You can find the location of the settings inside the repository settings -> Actions -> General -> Workflow permissions.

**Comment by fqw000** [comment]
> @DanielAlexssander You can find the location of the settings inside the repository settings -> Actions -> General -> Workflow permissions.

it works !

**Comment by MRSlouzk** [comment]
I have the same problem. What I want to do is pushing to another repository in the same organization. The branch I want to push is not under protect, workflow permission of org and two repositories are 'Read and write permissions' . I had tried to use my personal serects and GITHUB_TOKEN, but it 
 continuously run into "permission denied"
actions.yml
```yaml
permissions: write-all
```

**Comment by ZPascal** [comment]
Hi @MRSlouzk, it's necessary that you handle it with a personal access token. The GITHUB_TOKEN is restricted, and it's only [possible](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#about-the-github_token-secret) to interact with the repository which the triggers the GH action.

**Comment by kuldeep-bhimani** [comment]
> > @ad-m here it is, says read and write ![image](https://user-images.githubusercontent.com/2881159/127678772-776865c9-ca74-449b-a6df-8e95a0471560.png)
> > In your reference (cbosa run), you were pushing to master, I am trying to push to PR branch.
> 
> For anyone else getting a `Permission denied` error: This fixed it for me.

This worked for me as well.

**Comment by kuldeep-bhimani** [comment]
> > @ad-m here it is, says read and write ![image](https://user-images.githubusercontent.com/2881159/127678772-776865c9-ca74-449b-a6df-8e95a0471560.png)
> > In your reference (cbosa run), you were pushing to master, I am trying to push to PR branch.
> 
> where is this?

You will find it under the repo setting and then click on action

**Comment by lightlessdays** [comment]
Hi. Here is a simple trick to solve this issue:
1. Open GitHub Repository where the problem is occurring.
2. Go to Settings.
3. Go to Actions.
4. Go to General.
![image](https://github.com/ad-m/github-push-action/assets/97734029/6131202b-2850-43fe-a629-320a2e7c6e12)
5. Scroll down to Workflow permissions.
6. Make sure the following settings are enabled and click "Save"

![image](https://github.com/ad-m/github-push-action/assets/97734029/42daa9cd-e28c-4eac-a952-a6fcf7b1458d)

**Comment by danielo515** [comment]
Can someone explain me why this wonderful action works without problems with the default settings (just `Read repository contents and packages permissions`) when running in pushes to the main branch, but when it runs as part of a pull request (ie tries to push back to the PR) I need to setup the workflow permissions as instructed above (https://github.com/ad-m/github-push-action/issues/96#issuecomment-1647904286)?
Not saying it is a big problem, but my brain needs to understand. Thanks

**Comment by ShlomiRex** [comment]
> Hi. Here is a simple trick to solve this issue:
> 
> 1. Open GitHub Repository where the problem is occurring.
> 2. Go to Settings.
> 3. Go to Actions.
> 4. Go to General.
>    ![image](https://user-images.githubusercontent.com/97734029/255602791-6131202b-2850-43fe-a629-320a2e7c6e12.png)
> 5. Scroll down to Workflow permissions.
> 6. Make sure the following settings are enabled and click "Save"
> 
> ![image](https://user-images.githubusercontent.com/97734029/255602921-42daa9cd-e28c-4eac-a952-a6fcf7b1458d.png)

Still doesn't work (JamesIves/github-pages-deploy-action@v4.4.3)

**Comment by adpit** [comment]
> @DanielAlexssander You can find the location of the settings inside the repository settings -> Actions -> General -> Workflow permissions.

Thank Youu

**Comment by panienkaczuprynienka** [comment]
> > > @ad-m here it is, says read and write ![image](https://user-images.githubusercontent.com/2881159/127678772-776865c9-ca74-449b-a6df-8e95a0471560.png)
> > > In your reference (cbosa run), you were pushing to master, I am trying to push to PR branch.
> > 
> > 
> > where is this?
> 
> You will find it under the repo setting and then click on action

Worked for me too! Thanks!

**Comment by Olalexy1** [comment]
> Hi. Here is a simple trick to solve this issue:
> 
> 1. Open GitHub Repository where the problem is occurring.
> 2. Go to Settings.
> 3. Go to Actions.
> 4. Go to General.
>    ![image](https://private-user-images.githubusercontent.com/97734029/255602791-6131202b-2850-43fe-a629-320a2e7c6e12.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE2MTk2MDQsIm5iZiI6MTcwMTYxOTMwNCwicGF0aCI6Ii85NzczNDAyOS8yNTU2MDI3OTEtNjEzMTIwMmItMjg1MC00M2ZlLWE2MjktMzIwYTJlN2M2ZTEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAzVDE2MDE0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwYmRjZTUzZTk3YWUxOTBhYWU4YzQzZjMzNzU3MzA3YmEyZDdlNDA1NDFjODI2OTNkNjIwNDhmYzMyYjZmMzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6FBu5ZH7w0zmvEDpVJAHuTpQZ3l6iCmsHh_w0CvXQUs)
> 5. Scroll down to Workflow permissions.
> 6. Make sure the following settings are enabled and click "Save"
> 
> ![image](https://private-user-images.githubusercontent.com/97734029/255602921-42daa9cd-e28c-4eac-a952-a6fcf7b1458d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE2MTk2MDQsIm5iZiI6MTcwMTYxOTMwNCwicGF0aCI6Ii85NzczNDAyOS8yNTU2MDI5MjEtNDJkYWE5Y2QtZTI4Yy00ZWFjLWE5NTItYTZmY2Y3YjE0NThkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAzVDE2MDE0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4OGZiMTQwYTVkMTM5YTMyZGRiZTVmNGYzNDdhODk4ODczMzA3NmM2MTI5YWUxMmE1ZWY3OGE4OGI4YWJmZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OBbU76oSQ6x89dTMWLlKF8Hayw6XXVyBDjd3bPAhqrE)

Thanks alot for this

**Comment by marknoble** [comment]
> > Hi. Here is a simple trick to solve this issue:
> > 
> > 1. Open GitHub Repository where the problem is occurring.
> > 2. Go to Settings.
> > 3. Go to Actions.
> > 4. Go to General.
> >    ![image](https://private-user-images.githubusercontent.com/97734029/255602791-6131202b-2850-43fe-a629-320a2e7c6e12.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE2MTk2MDQsIm5iZiI6MTcwMTYxOTMwNCwicGF0aCI6Ii85NzczNDAyOS8yNTU2MDI3OTEtNjEzMTIwMmItMjg1MC00M2ZlLWE2MjktMzIwYTJlN2M2ZTEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAzVDE2MDE0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwYmRjZTUzZTk3YWUxOTBhYWU4YzQzZjMzNzU3MzA3YmEyZDdlNDA1NDFjODI2OTNkNjIwNDhmYzMyYjZmMzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6FBu5ZH7w0zmvEDpVJAHuTpQZ3l6iCmsHh_w0CvXQUs)
> > 5. Scroll down to Workflow permissions.
> > 6. Make sure the following settings are enabled and click "Save"
> > 
> > ![image](https://private-user-images.githubusercontent.com/97734029/255602921-42daa9cd-e28c-4eac-a952-a6fcf7b1458d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE2MTk2MDQsIm5iZiI6MTcwMTYxOTMwNCwicGF0aCI6Ii85NzczNDAyOS8yNTU2MDI5MjEtNDJkYWE5Y2QtZTI4Yy00ZWFjLWE5NTItYTZmY2Y3YjE0NThkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAzVDE2MDE0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4OGZiMTQwYTVkMTM5YTMyZGRiZTVmNGYzNDdhODk4ODczMzA3NmM2MTI5YWUxMmE1ZWY3OGE4OGI4YWJmZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OBbU76oSQ6x89dTMWLlKF8Hayw6XXVyBDjd3bPAhqrE)
> 
> Thanks alot for this

The images look broken here... it's hard to tell what settings you suggest enabling without them. 🤔

**Comment by ZPascal** [comment]
@marknoble You can also follow [this](https://github.com/ad-m/github-push-action/issues/96#issuecomment-1647904286) recommendation to handle access rights.

**Comment by ZPascal** [comment]
@marknoble Could you please explain your use case? Maybe you need a PAT.

**Comment by marknoble** [comment]
> @marknoble Could you please explain your use case? Maybe you need a PAT.

Fortunately/unfortunately I nuked my repo and did a fork on the project I was trying to emulate. For whatever reason, that solved the issue for me.

I had initially manually created the folder structure and files.

I wish I knew what I was doing wrong, but forking from the working project resolved the issue for me. 🤷‍♂️

**Comment by ZPascal** [comment]
>I wish I knew what I was doing wrong, but forking from the working project resolved the issue for me.

@marknoble That sounds great. Maybe you've specified the wrong reference or it's necessary to use the `force` option for the initial commit.

**Comment by aangelinsf** [comment]
Came here to see why my workflow was failing. It took adding permissions so that Dependabot could modify the pull-request and push the changes back to the repo:
    permissions:
      contents: write
      pull-requests: write

**Comment by Tungobhadra** [comment]
> Hi. Here is a simple trick to solve this issue:
> 
> 1. Open GitHub Repository where the problem is occurring.
> 2. Go to Settings.
> 3. Go to Actions.
> 4. Go to General.
>    ![image](https://private-user-images.githubusercontent.com/97734029/255602791-6131202b-2850-43fe-a629-320a2e7c6e12.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0ODY3NDYsIm5iZiI6MTcwNDQ4NjQ0NiwicGF0aCI6Ii85NzczNDAyOS8yNTU2MDI3OTEtNjEzMTIwMmItMjg1MC00M2ZlLWE2MjktMzIwYTJlN2M2ZTEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDIwMjcyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1MTcwYzZiZDYwZWNiZTAxNzk1YzU0NjlhZjFlNzMyNzk0OWJiYjk0ZjQyZDEzMWM3M2E0YzM0NTljYWVjYzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8ZCdnoDJnq79VZNshUT7TKm1ZDgClcH19iQ4_wl7IQY)
> 5. Scroll down to Workflow permissions.
> 6. Make sure the following settings are enabled and click "Save"
> 
> ![image](https://private-user-images.githubusercontent.com/97734029/255602921-42daa9cd-e28c-4eac-a952-a6fcf7b1458d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0ODY3NDYsIm5iZiI6MTcwNDQ4NjQ0NiwicGF0aCI6Ii85NzczNDAyOS8yNTU2MDI5MjEtNDJkYWE5Y2QtZTI4Yy00ZWFjLWE5NTItYTZmY2Y3YjE0NThkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDIwMjcyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlMDFiODVmZTNlYTdmYTAxOWI5ZTcxYTM4MTE4OTFmZjY4NzVkNTNkYWM3ODMxODcwNGJmMzljZGQ3Nzc0MWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.O-kOgfDve8v2OSu9Oou5aTGduiPNYlcY2-rMKdrASEs)

This really worked

**Comment by klaus-cicd** [comment]
> > Hi. Here is a simple trick to solve this issue:
> > 
> > 1. Open GitHub Repository where the problem is occurring.
> > 2. Go to Settings.
> > 3. Go to Actions.
> > 4. Go to General.
> >    ![image](https://user-images.githubusercontent.com/97734029/255602791-6131202b-2850-43fe-a629-320a2e7c6e12.png)
> > 5. Scroll down to Workflow permissions.
> > 6. Make sure the following settings are enabled and click "Save"
> > 
> > ![image](https://user-images.githubusercontent.com/97734029/255602921-42daa9cd-e28c-4eac-a952-a6fcf7b1458d.png)
> 
> Still doesn't work (JamesIves/github-pages-deploy-action@v4.4.3)
> 
> I get:
> 
> ```
> remote: Permission to ShlomiRex/pathfinding-algorithms-visualization.git denied to github-actions[bot].
> fatal: unable to access 'https://github.com/ShlomiRex/pathfinding-algorithms-visualization.git/': The requested URL returned error: 403
> ```
> 
> EDIT: Never mind, because I'm using webpack/babel and generate files (generating static HTML, JS, CSS files from react project), I added this write premission and now it works:
> 
> ```
> permissions:
>   contents: write # We generate static HTML, JS, CSS so we need write access to the repo
>   pages: write
>   id-token: write
> ```

Thanks

**Comment by XingXiaoWu** [comment]
> 在这里，说读和写 ![图像](https://user-images.githubusercontent.com/2881159/127678772-776865c9-ca74-449b-a6df-8e95a0471560.png)
> 
> 在您的参考（cbosa 运行）中，您正在推动 master，我正在尝试推动 PR 分支。

To avoid anyone being unable to find it,  here

![image](https://github.com/ad-m/github-push-action/assets/22769131/5c96b3bc-e341-440d-b16b-79be27ac8cce)

**Comment by rayliu445** [comment]
> > [@ad-m](https://github.com/ad-m) here it is, says read and write ![image](https://user-images.githubusercontent.com/2881159/127678772-776865c9-ca74-449b-a6df-8e95a0471560.png)
> > In your reference (cbosa run), you were pushing to master, I am trying to push to PR branch.
> 
> For anyone else getting a `Permission denied` error: This fixed it for me.

Solved my problem, thanks

**Comment by sorenwacker** [comment]
Hm, I cannot change that option:

<img width="793" alt="Image" src="https://github.com/user-attachments/assets/d1e18c71-fef1-4290-ae5c-153145d2d9bb" />

**Comment by SerhiiCho** [comment]
I'm the owner, but I also cannot change it

**Comment by huanfachen** [comment]
Have you checked the permission setting in publish.yml? I solved a similar problem by changing `contents: read` to `contents: write` under `permissions` tab in publish.yml. The other settings under `permissions` are unrelevant and can be removed.
